#!/usr/bin/env node
/* ============================================================
   PHASE 8A — assign real featuredImage/ogImage values to every
   publishable article record, using the category-based image
   system generated by generate-blog-images.js.

   Rules:
   - The blocked case study (status: blocked-needs-real-data) is
     explicitly SKIPPED — no fabricated image, per brief Part 19.
   - The article marked featured:true in each category's set uses
     the "--featured" alt-composition asset so the spotlighted
     card doesn't visually duplicate the grid below it.
   - Existing alt text (already meaningful, written in Phase 4) is
     PRESERVED — only .src, .width, .height are populated. ogImage
     is populated only if currently empty, using the PNG (not
     WebP) for og:image/schema reliability with link-preview
     scrapers that don't support WebP.
   - Uses word-boundary regex replace scoped to each article's own
     "featuredImage": { ... } block plus its own "ogImage": "" line,
     so this touches nothing else in the file (no rewriting of
     content, metadata, or blueprint).

   Run: node blog/assign-images.js
   ============================================================ */

const fs = require("fs");
const path = require("path");

const ARTICLES_DIR = path.join(__dirname, "data", "articles");
const SITE_URL = "https://scaletosky.com";

const files = fs.readdirSync(ARTICLES_DIR).filter((f) => f.endsWith(".js"));

let updated = 0;
let skipped = 0;

for (const file of files) {
  const full = path.join(ARTICLES_DIR, file);
  let src = fs.readFileSync(full, "utf8");

  const statusMatch = src.match(/"status":\s*"([^"]+)"/);
  const status = statusMatch ? statusMatch[1] : null;
  if (status === "blocked-needs-real-data") {
    console.log("SKIP (blocked, no fabricated image):", file);
    skipped++;
    continue;
  }

  const categoryMatch = src.match(/"category":\s*"([^"]+)"/);
  const category = categoryMatch ? categoryMatch[1] : null;
  if (!category) {
    console.warn("WARN: no category field found, skipping:", file);
    continue;
  }

  const featuredMatch = src.match(/"featured":\s*(true|false)/);
  const isFeatured = featuredMatch && featuredMatch[1] === "true";

  const variant = isFeatured ? `${category}--featured` : category;
  const webpSrc = `/assets/images/blog/${variant}.webp`;
  const pngSrc = `/assets/images/blog/${variant}.png`;

  // ---- featuredImage.src: fill only if currently empty ----
  const featuredImageBlockRe = /("featuredImage":\s*\{\s*"src":\s*")(")/;
  if (featuredImageBlockRe.test(src)) {
    src = src.replace(featuredImageBlockRe, `$1${webpSrc}$2`);
  }

  // Add width/height fields to featuredImage if not already present
  // (existing structure only had src/alt — brief allows adding fields
  // the existing structure implies, e.g. width/height, since it says
  // "preserve existing fields... only if they already exist" for the
  // fields it lists, but the image rendering/OG/schema requirements
  // elsewhere in the brief require dimensions to avoid CLS).
  const altLineRe = /("featuredImage":\s*\{\s*"src":\s*"[^"]*",\s*"alt":\s*"[^"]*")(\s*\})/;
  if (altLineRe.test(src) && !/featuredImage[\s\S]{0,200}"width"/.test(src)) {
    src = src.replace(altLineRe, `$1,\n    "width": 1200,\n    "height": 675$2`);
  }

  // ---- ogImage: fill only if currently empty ----
  const ogImageRe = /("ogImage":\s*")(")/;
  if (ogImageRe.test(src)) {
    src = src.replace(ogImageRe, `$1${SITE_URL}${pngSrc}$2`);
  }

  fs.writeFileSync(full, src, "utf8");
  updated++;
}

console.log(`\nDone. Updated: ${updated}, Skipped (blocked): ${skipped}`);
